# Site settings
title:          Bilal Haidar
description:    "It's all about coding"
url:            "https://bhaidar.github.io"

# Author
author:
  name:         Bilal Haidar
  url:          https://www.bilalhaidar.com
  email:        bhaidar@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
permalink:      /:year/:month/:title
paginate:       5

# Social Icons
twitter_username:     bhaidar
github_username:      bhaidar
linkedin_username:    
google_plus_username: 
facebook_username:    
dribbble_username:
