# Site settings
title:          Bilal Haidar
email:          bhaidar@gmail.com
description:    "It's all about coding"
url:            "https://www.bhaidar.dev"
logo:           "/favicon.ico"

# Author
author:
  name:         Bilal Haidar
  url:          https://www.bhaidar.dev
  email:        bhaidar@gmail.com
  twitter:      "bhaidar" #twitter:creator

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag

# Permalinks
permalink:      /:year/:month/:title
paginate:       5

# Social Icons
twitter_username:     bhaidar
github_username:      bhaidar
linkedin_username:    bilalhaidar
google_plus_username: 
facebook_username:    aspmvp
dribbble_username:

# SEO
twitter:
  username: bhaidar
  card: summary

# SEO Defaults
defaults:
  - scope:
      path:         ""
    values:
      image:
        path:       "/assets/apple-touch-icon-ipad-retina-152x152.png"
